services:
  testapp-postgresql-master:
    image: "bitnami/postgresql:14"
    ports:
      - "15432:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=testapp_database_read
      - POSTGRESQL_PASSWORD=toor
      - POSTGRESQL_POSTGRES_PASSWORD=toor
      - POSTGRESQL_DATABASE=testapp
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_REPLICATION_USE_PASSFILE=false
      - POSTGRESQL_EXTRA_FLAGS=--max_locks_per_transaction=256 --shared_buffers=1GB

  testapp-postgresql-replica:
    image: "bitnami/postgresql:14"
    ports:
      - "15433:5432"
    depends_on:
      - testapp-postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=testapp-postgresql-master
      - POSTGRESQL_PASSWORD=toor
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_REPLICATION_USE_PASSFILE=false
      - POSTGRESQL_EXTRA_FLAGS=--max_locks_per_transaction=256 --shared_buffers=1GB
